### ISSUE TITLE
Image size in custom dataset

### ISSUE THREAD

**Issue by MariaYsern** [explainingai-code/StableDiffusion-PyTorch#28]
Hi,

I am new in Stable Diffusion and I have a question about image sizes.

I have seen that in both examples of the dataset class (mnist_dataset.py and celeb_dataset.py), the images are always resized. Is this required for Stable Diffusion to work, or is it just recommended?

I have a custom dataset where each image has a different size and aspect ratio (e.g., 3456x2304, 2560x1920, 3696x2448, etc.). Can I remove the part of the code that resizes and crops the images?

Thanks in advance!

**Comment by explainingai-code** [comment]
Hello @MariaYsern ,
Typically they are indeed trained with images of one size and this code expect images during training to be of the same size. Alse the resolutions that you have mentioned are too high and would require huge amount of compute and time.
So I would keep the and resize and cropping of images.

**Comment by MariaYsern** [comment]
Hi @explainingai-code,

Thank you very much for your response!

I have started training the autoencoder, and as you mentioned, I quickly realized that images larger than 256x256 don't fit into my GPU memory. I'll continue resizing and cropping the images as suggested.

Thanks again for the help!
