### ISSUE TITLE
Using VAE instead of VQVAE

### ISSUE THREAD

**Issue by btjanaka** [explainingai-code/StableDiffusion-PyTorch#29]
Hi! Thank you for this really well-organized code! The README mentions that it is really easy to switch from VQVAE to VAE for the model training. I am wondering how I might go about doing that. Is it a matter of simply swapping the VQVAE model with the VAE model in parts of the code like in `train_vqvae.py`? Thank you!

**Comment by explainingai-code** [comment]
@btjanaka  Thank you for the appreciation :) .
Yes, simply switching the class from VQVAE to VAE + some minor changes will allow one to train VAE.
I have another repo for ControlNet in which I use VAE Autoencoder and provide LDM with VAE training and inference code - https://github.com/explainingai-code/ControlNet-PyTorch?tab=readme-ov-file#training-autoencoder-for-ldm

So if you want to train LDM with VAE just ignore the final ControlNet training step and thats it. 
Do let me know if end up facing any issues using that repo.

**Comment by btjanaka** [comment]
@explainingai-code Thank you for such a fast reply! The ControlNet repo worked great for me. Once again, I have to say that the code and explanations are really high-quality; I was looking for latent diffusion models for MNIST for many days and could not find any good ones until I got to yours. I'll reach out if I have any further questions :)
