### ISSUE TITLE
Question on normalization input regarding the perceptual loss

### ISSUE THREAD

**Issue by tonyyunyang** [explainingai-code/StableDiffusion-PyTorch#30]
Hi,
Considering the ScalingLayer reuses the mean and std deviation of ImageNet normalizing the input to the range of -1 and 1. Does it mean that it is necessary to scale the input to the range of -1 and 1 as well?
Best,
Tony

https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/ac8fb10825aae4416e099900cb4d2919732222ae/models/lpips.py#L136

**Comment by explainingai-code** [comment]
Hello @tonyyunyang ,
Yes. As you rightly pointed out, [these](https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/ac8fb10825aae4416e099900cb4d2919732222ae/models/lpips.py#L142) mean and std values are meant to achieve imagenet normalization on images scaled from -1 to 1, thats why the dataset always [scales](https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/ac8fb10825aae4416e099900cb4d2919732222ae/dataset/mnist_dataset.py#L91) images to this range even during autoencoder training. The other option is to keep using images scaled from 0-1 but in the lpips forward call pass `normalize` as True and it will do the scaling it needs [here](https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/ac8fb10825aae4416e099900cb4d2919732222ae/models/lpips.py#L105)

**Comment by tonyyunyang** [comment]
Hi @explainingai-code ,
Thanks for the explanation!
