### ISSUE TITLE
Question - Why using VAE and not just UNet to predict the final output image?

### ISSUE THREAD

**Issue by jpmcarvalho** [explainingai-code/StableDiffusion-PyTorch#6]
Hello,

First of all thank you for your great work!

I have a question about the use of VAE. Why don't use only UNet to predict the generated image?

**Comment by explainingai-code** [comment]
Hello,

Thank you for the appreciation. We can indeed just have UNet model and not have vae at all. That was the approach used by authors of [DDPM](https://arxiv.org/pdf/2006.11239.pdf) which I have implemented [here](https://github.com/explainingai-code/DDPM-Pytorch) . 
But while that works when images are smaller say 64x64, the training time and computational cost to train that on larger  images, say of size 512x512, is huge. 
So instead the authors of LDM first downscale the image from hi res pixel space(512x512) to a lower res latent space(64x64 using a vae with downscale factor of 8) and train UNet for diffusion in this latent space.

Hope this helps.

**Comment by jpmcarvalho** [comment]
Thank you very much for you reply! Completely understood your answer.

**Comment by explainingai-code** [comment]
Happy to help!
